package exampleApp;


/**
* exampleApp/tp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exampleApp.idl
* Sunday, June 4, 2023 7:34:52 PM ICT
*/

public interface tp extends tpOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface tp
