package exampleApp;


/**
* exampleApp/tpHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exampleApp.idl
* Saturday, June 3, 2023 5:52:08 PM ICT
*/

abstract public class tpHelper
{
  private static String  _id = "IDL:exampleApp/tp:1.0";

  public static void insert (org.omg.CORBA.Any a, exampleApp.tp that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static exampleApp.tp extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (exampleApp.tpHelper.id (), "tp");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static exampleApp.tp read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_tpStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, exampleApp.tp value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static exampleApp.tp narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof exampleApp.tp)
      return (exampleApp.tp)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      exampleApp._tpStub stub = new exampleApp._tpStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static exampleApp.tp unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof exampleApp.tp)
      return (exampleApp.tp)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      exampleApp._tpStub stub = new exampleApp._tpStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
