package exampleApp;

/**
* exampleApp/tpHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exampleApp.idl
* Sunday, June 4, 2023 7:34:52 PM ICT
*/

public final class tpHolder implements org.omg.CORBA.portable.Streamable
{
  public exampleApp.tp value = null;

  public tpHolder ()
  {
  }

  public tpHolder (exampleApp.tp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = exampleApp.tpHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    exampleApp.tpHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return exampleApp.tpHelper.type ();
  }

}
