package exampleApp;


/**
* exampleApp/tpOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exampleApp.idl
* Sunday, June 4, 2023 7:34:52 PM ICT
*/

public interface tpOperations 
{
  float add (float a, float b);
  float sub (float a, float b);
  float mul (float a, float b);
  float div (float a, float b);
} // interface tpOperations
