package exampleApp;


/**
* exampleApp/tpOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exampleApp.idl
* Saturday, June 3, 2023 5:52:08 PM ICT
*/

public interface tpOperations 
{
  float add (float a, float b);
} // interface tpOperations
